### ISSUE TITLE
Background processing does not work as described in docs

### ISSUE THREAD

**Issue by daksamit** [kreteshq/kretes#110]
Kretes: 0.71
OS: Ubuntu 20.04 LTS

According to: https://kretes.dev/docs/guide/in-depth/background-processing/

I created example task in tasks/SendEmail.ts and run `kretes background` in nix-shell

1. By default it listens on postgresql default port instead 5454
```
ks background

Run background processing

Options:
  -h, --help     Show help                                             [boolean]
  -V, --version  Show version number                                   [boolean]

Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
```
`export PGPORT=5454` solves this problem but

2. Kretes is looking for tasks in dist/tasks directory instead of tasks
```
ks background

Run background processing

Options:
  -h, --help     Show help                                             [boolean]
  -V, --version  Show version number                                   [boolean]

Error: Could not find tasks to execute - '/home/daksamit/dev/kretes_demo/dist/tasks' does not exist
    at Object.getTasks [as default] (/home/daksamit/.config/nvm/12.13.0/lib/node_modules/kretes/node_modules/graphile-worker/dist/getTasks.js:57:15)
    at async assertTaskList (/home/daksamit/.config/nvm/12.13.0/lib/node_modules/kretes/node_modules/graphile-worker/dist/runner.js:24:30)
    at async Object.exports.run (/home/daksamit/.config/nvm/12.13.0/lib/node_modules/kretes/node_modules/graphile-worker/dist/runner.js:51:47)
    at async Object.exports.handler (/home/daksamit/.config/nvm/12.13.0/lib/node_modules/kretes/dist/cli/background/start.js:37:21)
```

I copied task to dist/tasks and now `ks bg` output is:
```
[core] INFO: Worker connected and looking for jobs... (task names: '')
(node:20119) UnhandledPromiseRejectionWarning: Error: Failed 10 times in a row to acquire job; latest error: No runnable tasks!
    at doNext (/home/daksamit/.config/nvm/12.13.0/lib/node_modules/kretes/node_modules/graphile-worker/dist/worker.js:86:36)
    at Timeout.<anonymous> (/home/daksamit/.config/nvm/12.13.0/lib/node_modules/kretes/node_modules/graphile-worker/dist/worker.js:93:56)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
(node:20119) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20119) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

3. 
Missing comma `SendEmail` instead of `SendEmail,` in example and broken 'edit this page on github' link in [docs](https://kretes.dev/docs/guide/in-depth/background-processing/)
![image](https://user-images.githubusercontent.com/7165997/96278193-817f8200-0fd5-11eb-9000-5b0a988f8923.png)

**Comment by daksamit** [comment]
Ad. 2 
It looks like when looking for jobs, crashes after time.
Also when I tried to run `ks bg schedule SendEmail '{ "to": "admin@example.com" }'` while looking for jobs, it does nothing.

**Comment by zaiste** [comment]
@daksamit could you show me your `config/default.json` ?

**Comment by daksamit** [comment]
```
{
  "db": {
    "database": "postgres",
    "username": "daksamit"
  },
  "deploy": {
    "client": {
      "delete": true,
      "dest": "YOUR DESTINATION",
      "src": "dist/"
    },
    "server": {
      "delete": true,
      "dest": "YOUR DESTINATION",
      "exclude": [
        "dist",
        "node_modules",
        ".git",
        "static/upload",
        "config/default.yaml"
      ],
      "src": "."
    }
  }
}

```

I assume it's related to `deploy.src` ?

**Comment by zaiste** [comment]
Thanks! It looks good. Could you show me your `default.nix` ? Also, once you are in project directory, could you do 

```
echo $PGPORT
```

There is **no** need to explicitly run `nix-shell`. You should however do `direnv allow` when you do `cd <your-project` for the first time.

**Comment by daksamit** [comment]
default.nix
```
{ pkgs ? import <nixpkgs> {}
}:
pkgs.mkShell {
  name = "kretes_demo-environment";
  buildInputs = [
    pkgs.nodejs-14_x
    pkgs.postgresql_12
    pkgs.pgcli
  ];
  shellHook = ''
    export PGDATA=./db/content
    export PGDATABASE=kretes_demo
    export PGPORT=5454
    export PGSSLMODE=disable
  '';
}
```
and I have empty output running echo $PGPORT

**Comment by zaiste** [comment]
Thanks for doing that. Something is wrong indeed. I'm investigating. Here's how I run a project on my end. Could you confirm you're doing roughly the same steps ?

![2020-10-16 18 23 07](https://user-images.githubusercontent.com/200613/96283861-176adb00-0fdd-11eb-92f1-75d46169f2c8.gif)

**Comment by zaiste** [comment]
@daksamit that's my fault. The docs are not OK. I'll fix them. Could you do

```
sudo apt install direnv
```

and then add 

```
eval "$(direnv hook bash)"
```

at the end of your `.bashrc` followed by 

```
source ~/.bashrc
```

?

**Comment by zaiste** [comment]
@daksamit 

- [x] missing comma FIXED
- [x] Edit in GitHub button FIXED
- [x] `tasks/` directory handling FIXED
- [x] more explicit docs ADDED

Please update Kretes to `0.73.0`
